### ISSUE TITLE
python

### ISSUE THREAD

**Issue by SamixxHueYT** [ClanGenOfficial/clangen#930] opened 2023-03-10 04:02 UTC
Hi! Im trying to get clangen on my chromebook, since it doesnt specify if you can or cant in the code area for python. it doesnt say that either code for python is available; it says error2, and i dont know how to 'install' the thing. im so bad at explaining holy fuck. oh, and, by the way, Will you ever make a faster way for chromebooks or a way for chromebook or general? i only get to play it with clangen mobile from a clangen 'mod', and it keeps deleting my data. Please, **Please, PLEASE** Make a way for chromebook or mobile devices. theres other people besides me who want to play it, but cant because we dont have the neccesary devices.

Sorry if that was long! :)

**Comment by MeetoazBhardwaj** [comment] 2023-03-10 04:09
Hi there! I'm sorry to hear you're having trouble installing clangen on your Chromebook. To install clangen, you'll need to follow a few steps:

1. Open the Terminal app on your Chromebook.
2. Type "sudo apt-get update" (without quotes) and hit enter. This will update the package manager on your Chromebook.
3. Type "sudo apt-get install clang" (without quotes) and hit enter. This will install the clang compiler on your Chromebook.
4. Once the installation is complete, you should be able to use clangen.

![A cute cat](https://camo.githubusercontent.com/0cc346939e2faecfeeada663a166ef2bd648a14453609b1cb4725daf9ea6b50a/68747470733a2f2f692e70696e696d672e636f6d2f6f726967696e616c732f65332f30622f39302f65333062393065633032343865616462366662633634616133643639653336312e6a7067)

**Comment by SamixxHueYT** [comment] 2023-03-10 04:14
Thank you! How do I know when it's done? Right now it's just abunch of
selecting,  unpacking and preparing to unpack. Lol

**Comment by MeetoazBhardwaj** [comment] 2023-03-10 04:29
When you run the command 
`sudo apt-get install libsdl1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsdl-image1.2-dev`
 
it will prompt you for confirmation to install these packages. You can press "y" to confirm and begin the installation process.

Once the installation is complete, you should see a message indicating that the process was successful. You can then move on to the next steps to download and compile the Clangen source code.

![funny cat](https://media.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif)

**Comment by SamixxHueYT** [comment] 2023-03-10 04:52
I'm sorry if I'm bothering you cuz u have to reply all the time but I am
having a heck of a time-

It was unable to read everything besides the state info, dependency tree
and package lists, there's nothing happening when I press Y.

**Comment by SamixxHueYT** [comment] 2023-03-10 04:54
Oh, and I also dunno if I have to reset this entire thinggggg-

**Comment by MeetoazBhardwaj** [comment] 2023-03-10 05:07
No problem at all! meow here🪄😸.

it could be because of a missing dependency or an issue with your package manager.

Here are some steps you can try to fix the issue:

1. Try running "sudo apt-get update" again to ensure that your package list is up to date.
2. Make sure you have the latest version of pip installed by running `pip install --upgrade pip`.
3. Try running `sudo apt-get install build-essential` to install some basic development tools that Clangen might need.
4. If none of these steps work, try installing Clangen using a virtual environment. You can create a virtual environment by running the following command: `python3 -m venv myenv` (replace "myenv" with the name of your choice). Then activate the virtual environment by running `source myenv/bin/activate`. Finally, install Clangen using pip: `pip install clangen`.

If you're still having issues with the installation, let me know and I'll try to help you further.

![sup](https://media.giphy.com/media/BMaE0wCQhcJj2/giphy.gif)

**Comment by SamixxHueYT** [comment] 2023-03-10 05:40
I think I have everything, but it says, 'pip command not found'and 'missing
destination file operand after clangen Try install --help for more info'

**Comment by MeetoazBhardwaj** [comment] 2023-03-10 08:54
The error message "pip command not found" means that pip is not installed on your system or it is not added to your PATH environment variable.

or missing a destination file operand, as the error message suggests.

I hope these helps,

I found this link so you can play on Chromebook browser by going here
https://clangen-web.github.io/

https://www.youtube.com/watch?v=B_u38QwW6fc
https://www.reddit.com/r/WarriorCats/comments/y4yu46/guide_on_how_to_install_and_play_clangen/
https://www.reddit.com/r/WarriorCats/comments/wp9zbv/clangen_on_chromebook/


![cat](https://media.giphy.com/media/fSpafmcMG4FzPrnmnw/giphy.gif)

**Comment by BharathSatheeshKumar** [comment] 2023-03-10 16:29
It sounds like you're encountering an issue when trying to install Clangen on your Chromebook. This could be caused by a few different factors, such as a network issue or an issue with the package manager.

 Before installing Clangen, make sure your package manager is up to date,by using 
`sudo apt-get update`

Try installing Clangen again: Once you've updated your package manager, try installing Clangen again by running this:
`sudo apt-get install clangen`

If you're still encountering issues, you may want to try using a different package manager, such as Snap or Flatpak, to install Clangen.

**Comment by scribblecrumb** [comment] 2023-03-11 17:04
> Hi! Im trying to get clangen on my chromebook, since it doesnt specify if you can or cant in the code area for python. it doesnt say that either code for python is available; it says error2, and i dont know how to 'install' the thing. im so bad at explaining holy fuck. oh, and, by the way, Will you ever make a faster way for chromebooks or a way for chromebook or general? i only get to play it with clangen mobile from a clangen 'mod', and it keeps deleting my data. Please, **Please, PLEASE** Make a way for chromebook or mobile devices. theres other people besides me who want to play it, but cant because we dont have the neccesary devices.
> 
> Sorry if that was long! :)

Hey there! We're fairly certain the accounts trying to help you are bots.  Please don't follow the directions they gave you as they seem to be nonsense and won't be helpful.  I'm going to go ahead and close this issue for now.

**Closed as completed by scribblecrumb** 2023-03-11 17:04 UTC

**Comment by lillithrosepup** [comment] 2023-03-11 17:24
You can get actual help at our [Discord](https://discord.gg/clangen)

**Comment by SamixxHueYT** [comment] 2023-03-11 18:50
Awesome, thanks!

**Comment by Sparkwhisker** [comment] 2024-01-28 18:18
I can't figure out how to use ClanGen! I tried using the Terminal app on my ChromeOs and I just can't figure it out!

**Comment by ari935** [comment] 2024-10-03 02:29
hey um I can't access clangen on inch io and the terminal app is banned is [there anthro way I can do it?
