### ISSUE TITLE
[BUG] crash upon victim history or murder reveal?

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2872] opened 2024-10-08 23:43 UTC
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i have like 0 clue why any of these bugs happen i am so sorry. upon moonskipping, the game crashed. a bunch of murders and reveals have happened before, but game crashed when a murder or reveal tried to happen. ill attach my save folder

**Grade**: (only select one)
- Important - The bug has a large effect on the gameplay but is not urgent

**Reproduce**
1. moon skip <3
2. pray it crashes

**Commit # or Game Version Number**: 

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1210, in one_moon_cat
    self.other_interactions(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 2097, in other_interactions
    handle_short_events.handle_event(event_type="misc",
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\handle_short_events.py", line 242, in handle_event
    History.reveal_murder(
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat\history.py", line 680, in reveal_murder
    victim_history = victim_history["is_victim"][0]
KeyError: 'is_victim'
https://drive.google.com/drive/folders/1SQeu3hSzTX2eIjwvWwz7mKrr8wHYhQy-?usp=sharing

**Comment by selkirks** [comment] 2024-10-08 23:48
related murder bug possibly?

Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1215, in one_moon_cat
    triggered_death = self.handle_injuries_or_general_death(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 2162, in handle_injuries_or_general_death
    triggered_death = Condition_Events.handle_injuries(cat, random_cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\condition_events.py", line 374, in handle_injuries
    handle_short_events.handle_event(event_type="health",
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\handle_short_events.py", line 237, in handle_event
    if "murder_reveal" in self.chosen_event.sub_type:
AttributeError: 'NoneType' object has no attribute 'sub_type'

**Comment by j-gynn** [comment] 2024-11-23 22:07
Likely duplicate of #2857

**Closed as completed** 2024-11-23 23:49 UTC
Labels: bug
