### ISSUE TITLE
[BUG] messed up murder/murder victim histories

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2301] opened 2024-05-02 16:58 UTC
**Type**: text/code

**Describe the bug**
Rabbitwater is murdered by Larkberry. Moon event lets user know _for sure_ that Larkberry was the murderer. Rabbitwater's death history says that they were murdered by an "unknown killer" and Larkberry has no mention of the murder in their history like other murders would.

**Grade**: Important

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/a1ed6340-24df-4bc9-8af1-da5f91b0dbe5)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/537a2aec-9e41-4d3a-a15e-7fb7ab328ae8)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/d6b18d4b-9336-41ee-8556-684f1f28194d)

EDIT:
The history did get updated when Larkberry admits the murder to another clanmate. I just think if the user knows that Larkberry killed Rabbitwater, that should still be mentioned in the history even if no one finds out about the truth

**Comment by joesandmeyer** [comment] 2024-05-04 15:57
Note that this is true for any unknown murderer. The user will see the event text first, and then it appears in the history as unknown until another cat discovers it. Currently it's intended behavior.

**Comment by scribblecrumb** [comment] 2024-06-10 01:50
Closing as intended behavior

**Closed as completed by scribblecrumb** 2024-06-10 01:50 UTC
