### ISSUE TITLE
[BUG] Inviting Mates with Leader's Den Causes A Crash

### ISSUE THREAD

**Issue by Sumwatt0** [ClanGenOfficial/clangen#2644] opened 2024-08-20 23:32 UTC
## Bug Report was written by snapshotmanor on Discord, I'm just copying it here.
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
_"Inviting in cats that are mates with Clan cats crashes the game. If they are not mates with Clan cats, they can be invited in like normal. However, this bug only affects SOME outsiders; and when it does, that outsider is perma bugged. No matter how many moons you timeskip, you can't invite them in, it crashes everytime. I tried timeskipping till the Clan cat moved on, and they were still bugged. I tested two cats, and the one that wasn't bugged never ended up crashing the game."_ - **snapshotmanor on Discord**

Update [9/20]: *"This issue is just generally when a cat is a former clan cat, not a mate. I've also noticed from testing that it seems that all of the former clan cats that crash my game have the loner3 backstory. I'm not sure if its former clan cats as a whole or just that, but all of the ones that I tested that crashed my game had that backstory for some reason."* - **snapshotmanor on Discord**

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. Go on border patrols until one of your Clan cats finds a mate outside the Clan that generates as an outsider, but doesn't join the Clan.
2. Go to the leader's den and invite that cat in. If the game crashes, that means that cat is perma bugged. If the game doesn't crash, that cat isn't bugged.

**Commit # or Game Version Number**: 
cacc01ce

**Screenshots**

https://github.com/user-attachments/assets/6a6d4cd9-c9da-4989-9b7f-e0c1e7b0afa0

![image](https://github.com/user-attachments/assets/534ca08b-bb2e-4956-ba0c-6e2d64ed70b5)

**Comment by j-gynn** [comment] 2024-11-23 22:30
Duplicate of #2887, will be closed by #3025

**Closed as completed** 2024-11-24 00:11 UTC
Labels: bug
