### ISSUE TITLE
[BUG] kit helps warrior back to camp

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2329] opened 2024-05-08 15:57 UTC
**Type**: code

**Describe the bug**
During war with neighboring clan, a warrior defends a kit and the kit helps the warrior back to camp. The kit probably _shouldn't_ be participating in clan wars

**Grade**: Regular

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/4fcf14a2-9e0f-40cc-ab3a-59272fafbab4)

**Comment by Oddlem** [comment] 2024-05-13 21:50
I think this is intended behavior, there's no check for that condition so it's just taking from the regular death dictionaries

**Comment by scribblecrumb** [comment] 2024-05-14 01:41
This will be addressed in #2264

**Comment by scribblecrumb** [comment] 2024-06-10 01:48
Hopefully fixed in #2256

**Closed as completed by scribblecrumb** 2024-06-10 01:48 UTC
