### ISSUE TITLE
Freshkill Issues

### ISSUE THREAD

**Issue by RedemptionistArc** [ClanGenOfficial/clangen#2186] opened 2024-04-03 04:56 UTC
Hello!! Hopefully this is the right place to report bugs now, ty mods for guiding me here <3
I'm on windows 11, newest version available (v.0.11.1) and the freshkill feature is entirely bugged out. First of all, it says that I have more than sufficient prey available to feed the whole Clan, but then I feed my Clan and only very few cats get fed. Second of all, I have the tactic set to nutrition first, so that those that are hungriest get fed first, yet when I feed my clan the first that get fed are cats that are already satiated. Now due to this huge bug, I've lost literally majority of my Clan due to starvation and frankly will have to delete this save because there's no saving a Clan that has like 3 kits left over, they can't feed themselves. Unfortunately I cannot play the game as of now due to this game-breaking bug. Thank you <3

**Comment by aBlackOnyxz** [comment] 2024-04-05 16:31
I am having the exact same issue! Same version, same tactic.
I also did a test with 20 prey and three cats at "satiated", clicked feed all around 3-5 times and instead of them being fed, one remained the same, one dropped to "hungry" and one dropped to "very hungry". I'll do another test and see if the tactic caused it?

**Comment by aBlackOnyxz** [comment] 2024-04-05 16:42
Update: I switched the tactic back to "By-Status" and the feed all button worked as intended, it may be an issue with the "Less Nutrition First" tactic.

**Comment by Lixxis** [comment] 2024-04-26 15:31
Should have been fixed with PR #2226

**Closed as completed by Lixxis** 2024-04-26 15:31 UTC
