### ISSUE TITLE
[BUG] random cat is associated in murder reveal

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2846] opened 2024-10-04 21:54 UTC
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
kariba has no relation to the murder or murder reveal, but is said to discover the murder in the murderer's and victim's history

**Grade**: (only select one)
- Unimportant - This bug has little to no impact on play. 

**Reproduce**
1. moon skip till a cat murders another
2. moon skip till the murderer reveals their crime to the clan
3. check the murderer's and victim's history

**Commit # or Game Version Number**:  e21871523586d97e06bd175613546a24ff5075fd

**Screenshots**
![image](https://github.com/user-attachments/assets/e2eeeeb8-6136-4f26-af96-359088cc1f46)
![image](https://github.com/user-attachments/assets/c23f9625-3689-4946-8ae9-a0265e128f34)
![image](https://github.com/user-attachments/assets/08c7f2a9-5748-4393-9f72-e441a545ab40)

**Comment by j-gynn** [comment] 2024-11-23 22:08
Possible duplicate of #2857, please confirm if this was noticed whilst speedrunning moonskips

**Closed as completed** 2024-11-23 23:49 UTC
Labels: bug, issue-in-text
