### ISSUE TITLE
[BUG] pregnancy causes game to crash

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2843] opened 2024-10-04 21:00 UTC
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
i was moon skipping to get a big clan but upon one of the moons being skipped, the game crashed. i presume it is somehow related to my leader being pregnant

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. make a new clan
2. have all pregnancy settings on true
3. moon skip

**Commit # or Game Version Number**: e21871523586d97e06bd175613546a24ff5075fd

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 708, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1193, in one_moon_cat
    Pregnancy_Events.handle_having_kits(cat, clan=game.clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 77, in handle_having_kits
    Pregnancy_Events.handle_two_moon_pregnant(cat, clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 364, in handle_two_moon_pregnant
    kits = Pregnancy_Events.get_kits(kits_amount, cat, other_cat, clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 874, in get_kits
    kitten.create_inheritance_new_cat()  # Calculate inheritance.
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat\cats.py", line 2588, in create_inheritance_new_cat
    self.inheritance = Inheritance(self, True)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 56, in __init__
    self.update_all_related_inheritance()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 144, in update_all_related_inheritance
    self.all_inheritances[cat_id].update_inheritance()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 107, in update_inheritance
    for inter_id, inter_cat in self.cat.all_cats.items():
RuntimeError: dictionary changed size during iteration
![image](https://github.com/user-attachments/assets/d5df7d74-ad8a-413a-988a-9e32cdbc648d)

**Comment by selkirks** [comment] 2024-10-08 23:32
got a potentially related crash:

Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1193, in one_moon_cat
    Pregnancy_Events.handle_having_kits(cat, clan=game.clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 77, in handle_having_kits
    Pregnancy_Events.handle_two_moon_pregnant(cat, clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 364, in handle_two_moon_pregnant
    kits = Pregnancy_Events.get_kits(kits_amount, cat, other_cat, clan)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\relationship\pregnancy_events.py", line 874, in get_kits
    kitten.create_inheritance_new_cat()  # Calculate inheritance.
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat\cats.py", line 2588, in create_inheritance_new_cat
    self.inheritance = Inheritance(self, True)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 56, in __init__
    self.update_all_related_inheritance()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 144, in update_all_related_inheritance
    self.all_inheritances[cat_id].update_inheritance()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 98, in update_inheritance
    self.init_siblings(inter_id, inter_cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\cat_relations\inheritance.py", line 486, in init_siblings
    for _c in self.cat.all_cats.values():
RuntimeError: dictionary changed size during iteration

**Comment by scribblecrumb** [comment] 2024-11-11 23:59
This couldn't be connected to the fast clicking issues we've been having, could it @selkirks ?

**Comment by selkirks** [comment] 2024-11-12 21:29
probably tbh. fast clicking creates a lot of issues regarding moon skips. so imo maybe a 'cooldown' to click it shld be created?

**Comment by j-gynn** [comment] 2024-11-23 22:09
Duplicate of #2857 - changing size is a hallmark of a race condition.

**Closed as completed** 2024-11-23 23:49 UTC
Labels: bug
