### ISSUE TITLE
Game Crashes when showing moon count on a cat that murdered someone [BUG] 

### ISSUE THREAD

**Issue by banananationminion** [ClanGenOfficial/clangen#2384] opened 2024-05-31 14:11 UTC
**Type**:
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
When clicking the moon count on a cat that has been revealed to have murdered someone, the game crashes and closes without saving.

**Grade**:
- Regular - A typical bug that should be seen to soon, but doesn’t necessarily break the game or inhibit the player

**Reproduce**
1. Go to cat history of a cat that has murdered another at one point or another and was found out, does not have to be right away
2. Click on the moon counter of the history box
3. See error

**Commit # or Game Version Number**: 
v0.11.2

**Additional context**
This happened twice, so I can confirm that the cat does not have to have the reveal right away. As soon as it is revealed, though, when you open the moon count, the game will crash.

**Screenshots**

![Screenshot (181)](https://github.com/ClanGenOfficial/clangen/assets/167690380/50796765-5fbe-4844-979f-1a9a50fbd7ba)

**Comment by j-gynn** [comment] 2024-06-01 20:21
Confirmed in 0.11.2, cannot reproduce in development branch. Seems this has been [fixed in the development branch here](https://github.com/ClanGenOfficial/clangen/blob/dba6e299ce6ff0b8aa1d52440e5d437fa5e864e6/scripts/screens/ProfileScreen.py#L1455C1-L1455C83).

**Comment by archanyhm** [comment] 2024-06-08 12:50
See comment above. Although we should start fixing stable bugs in stable as well.

**Closed as completed by archanyhm** 2024-06-08 12:50 UTC
