### ISSUE TITLE
[BUG] Crash when trying to open "Choose a Mate"

### ISSUE THREAD

**Issue by frumpkinisgod** [ClanGenOfficial/clangen#3155] opened 2024-12-11 09:24 UTC
### Type of bug

Code - general bugs related to how the game runs and responds to you.

### Description

When I clicked the choose mate option an error box with this text appeared:
Traceback (most recent call last):
  File "main.py", line 356, in <module>
  File "scripts\screens\ChooseMateScreen.py", line 367, in screen_switches
  File "scripts\screens\ChooseMateScreen.py", line 806, in update_current_cat_info
  File "scripts\cat\cats.py", line 3481, in determine_next_and_previous_cats
ValueError: CAT OBJECT:58 is not in list

My game then crashed

Trying a second time reproduced this error
Traceback (most recent call last):
  File "main.py", line 356, in <module>
  File "scripts\screens\ChooseMateScreen.py", line 367, in screen_switches
  File "scripts\screens\ChooseMateScreen.py", line 806, in update_current_cat_info
  File "scripts\cat\cats.py", line 3481, in determine_next_and_previous_cats
ValueError: CAT OBJECT:47 is not in list

### Grade

Important - The bug has a large effect on the gameplay but is not urgent

### Steps to reproduce the behavior

Go to cat profile
Press the pairing button
Error pops up
Game crashes

### Commit # or Game Version Number

v0.12.2

### Additional context

Not happening on every cat. More common on younger cats, but my first page of cats is totally fine. Save is 82 moons in and the cats with the error are 15 moons old or younger.

**Comment by rustykitty** [comment] 2024-12-12 17:01
Possible duplicate of #3147.

**Closed as completed** 2024-12-13 00:23 UTC
