### ISSUE TITLE
Game crash when sending cats on a hunting patrol

### ISSUE THREAD

**Issue by BlakeRipples** [ClanGenOfficial/clangen#1998] opened 2024-01-08 19:32 UTC
[Crash log.txt](https://github.com/ClanGenOfficial/clangen/files/13865543/Crash.log.txt)
Crash information is attached. I forgot the exact cats, but this was when I sent two non-related cats on a hunting patrol.

**Comment by Lixxis** [comment] 2024-01-09 11:01
Duplicate of #1994

**Closed as completed by Lixxis** 2024-01-09 11:01 UTC
Labels: duplicate
