### ISSUE TITLE
[BUG] Text is very slightly cut off at the bottom in cat page

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2338] opened 2024-05-14 13:43 UTC
**Type**: UI

**Describe the bug**
In any cat page, if you pay close attention, you can see the text is very very slightly cut at the bottom, visible only for letters like 'g', 'y' or 'p'.
EDIT: it also happens in the medicine den, for the cat's names; and for the conditions' tab.

**Grade**: Unimportant

**Reproduce**
Check the text inside any cat's page.

**Commit # or Game Version Number**: 1f8fb2e6c

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/c8ec0536-ca4c-4dde-afea-5375fb15c7e5)
To compare how this letters usually look like:
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/18882dc9-676e-459d-aa3e-dcd31c90b8ec)
At the medicine den:
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/86f5b41a-13e6-4c2a-8a92-3ed06fd4cabd)
Conditions:
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/dd99725b-9957-465d-b657-993e68cb70c8)

**Comment by keyraven** [comment] 2024-05-14 18:44
Note - this is one of the many small issues associated with the update to pygame_gui 0.6.10

**Comment by scribblecrumb** [comment] 2024-05-15 00:07
Most of these are caused by a limitation of pygui 0.6.10 regarding how decreased line spacing is displayed.  Medicine den name cut off is unrelated and thus fixable, but seems to be the only one.  #2342 fixes problems that are fixable.

**Comment by archanyhm** [comment] 2024-06-08 12:45
Should be fixed with #2342

**Closed as completed by archanyhm** 2024-06-08 12:45 UTC
Labels: bug, limitation
