### ISSUE TITLE
Strange behavior if Clan is named "Current"

### ISSUE THREAD

**Issue by ZtheCorgi** [ClanGenOfficial/clangen#1867] opened 2023-11-04 04:44 UTC
**Type:** code
**Summary:** if the "current clan" is named "currentclan", the game does not load it upon closing and reopening, even though "current" is listed in currentclan.txt. instead it seems to load whatever save is first in alphabetical order
**Grade:** regular
**Occurrence:** frequent
**Reproduce:** name a clan "currentclan" with at least one other clan that comes before it in alphabetical order. the clan the game opened instead for me was biteclan, for instance
**Commit:** 3645edf2b3a2c49c7a879f22410fb1ea854a7cd0

**Comment by ZtheCorgi** [comment] 2023-11-04 05:00
notably, for some reason clicking "switch clan" and then picking currentclan does seem to load the correct clan when the game is reopened. but simply saving and then closing + reopening loads the wrong clan

**Comment by keyraven** [comment] 2023-11-04 05:14
I am unable to replicate this issue.  I am running from source, python version 3.11.4.  I created the clan named "Current" and one named "Apple", and a third clan named "Iris". I opened IrisClan, then attempted to switch to CurrentClan. The clan switch happened without issue.  What version (packaged, from source) and platform are you running on?

**Comment by keyraven** [comment] 2023-11-04 05:15
I am also having no issues when closing the reopening the game with CurrentClan loaded. CurrentClan is reloaded as expected.

**Comment by ZtheCorgi** [comment] 2023-11-04 05:29
what.... is my game fucking haunted... why is it doing this to me. i am running off of development, from source, using VScode, on the commit i specified in my report. i am on python 3.10.11 but i will go ahead and update to 3.11.6 and see if anything changes

**Comment by ZtheCorgi** [comment] 2023-11-04 05:31
...okay. so updating python...fixed it maybe?? im now having trouble reproducing also. What in the World. i'm sorry i had no idea i was using an outdated version of python or...that it would cause that. why would it even do that.

**Comment by ZtheCorgi** [comment] 2023-11-04 06:16
ok never mind. it was NOT fixed. it just decided to work properly like...twice after i updated. for some reason. changing occurrence as a result i guess

**Comment by archanyhm** [comment] 2024-03-07 03:12
I could reproduce this; there's some quite peculiar corner cases coming together here. It's not a high priority though, so I might take some time to report back and fix this.

**Comment by ZtheCorgi** [comment] 2024-03-07 03:14
oh my god finally someone managed to reproduce it. thank you arch. would love more information on this, i am still scratching my head over why it only happens sometimes

**Comment by selkirks** [comment] 2024-03-10 14:27
> oh my god finally someone managed to reproduce it. thank you arch. would love more information on this, i am still scratching my head over why it only happens sometimes

in regards to why it happens, maybe its because of the currentclan file? the one that selects which clan youre on. not sure, just throwing out ideas

**Comment by ZtheCorgi** [comment] 2024-03-10 15:44
> in regards to why it happens, maybe its because of the currentclan file? the one that selects which clan youre on. not sure, just throwing out ideas

yeah, it seems pretty clear to me that that must have something to do with it. the confusing part, as i said, is that it only happens sometimes and not every time the game is reloaded

**Comment by joesandmeyer** [comment] 2024-04-30 04:19
I can't figure this one out but it still occurs sometimes

**Comment by PoppyBlossom** [comment] 2024-08-07 20:28
_(This is my very first comment on Github)_ I think I figured this out. I am running commit 7b48f10 from the source. I noticed that the clan currentClan removes currentclan.txt when it's being saved, causing the game to load the saves in alphabetical order and this happens: 
![image](https://github.com/user-attachments/assets/2f59b1c3-e715-4054-8aa0-653c7d50925b)
There may be some contradiction going on regarding file names.

**Comment by PoppyBlossom** [comment] 2024-08-07 20:48
Major progress! I found the exact line at which the file is being deleted. It's in scripts/clan.py, line 543
```
        if os.path.exists(get_save_dir() + f"/{self.name}clan.txt"):
            os.remove(get_save_dir() + f"/{self.name}clan.txt")
```
this if statement is probably there for compatible issues. But in this case, it deletes the currentclan.txt.

**Comment by PoppyBlossom** [comment] 2024-08-07 20:52
> yeah, it seems pretty clear to me that that must have something to do with it. the confusing part, as i said, is that it only happens sometimes and not every time the game is reloaded

The reason behind this is that it only happens when the currentClan is saved before closing.

**Closed as completed** 2024-08-18 20:33 UTC
Labels: bug, replication-confirmed
