### ISSUE TITLE
cat death event exists in the wrong clan

### ISSUE THREAD

**Issue by TABEE002** [ClanGenOfficial/clangen#1877] opened 2023-11-07 20:05 UTC
<img width="406" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/110104891/3c372426-24c0-4ae0-ba73-d701217e5142">
<img width="491" alt="image" src="https://github.com/ClanGenOfficial/clangen/assets/110104891/50af90c3-79fa-42ae-acbf-a9010b2a24be">

Version: v.0.10.5
Type: Code
Summary: Pinetooth died during a patrol, being killed by a dog after following a trespassing cats scent. I created a new clan and timeskipped a moon. the game mentions him dying in the new clan, even though he doesn't exist there. When I switch back to his clan. His death event (with possible grief) does not exist
Grade: Non-vital
Occurence: Unsure, probably permanent
Reproduce: Have a cat die during a patrol (not sure if it matters, but the patrol he died in was with a trespassing cat and a dog). Then, Don't timeskip. Save the game and make a new clan. Timeskip in this clan one moon. Then the death event should show up.

**Comment by keyraven** [comment] 2023-11-08 17:43
Duplicate of https://github.com/ClanGenOfficial/clangen/issues/1822

**Comment by keyraven** [comment] 2023-11-08 17:45
I apologize for marking as duplicate, I misread the issue.

**Comment by scribblecrumb** [comment] 2024-10-02 03:37
Was this fixed @j-gynn ?

**Comment by archanyhm** [comment] 2024-10-13 11:41
Issue is stale, therefore it's being closed. Reopen if it still persists.

**Closed as not planned by archanyhm** 2024-10-13 11:41 UTC
Labels: bug, 📍 Assigned
