### ISSUE TITLE
Installing requirements fails on Python 3.12

### ISSUE THREAD

**Issue by larkgz** [ClanGenOfficial/clangen#1852] opened 2023-10-30 23:19 UTC
`requirements.txt` and `pyproject.toml` request that python < 3.12, but 3.12 has been released as the newest Python version.

**Comment by archanyhm** [comment] 2023-11-01 10:09
Adjusted the label since the constraint has been added deliberately. Feel free to adjust the constraint to include 3.12 and check for compatibility/stability on that version so we could potentially bump from 3.11 to 3.12 — but since out target versions are 3.8 and 3.11 respectively as of now, everything is working as intended.

**Comment by Thlumyn** [comment] 2023-12-27 16:07
Closing as no plan to change as of now.

**Closed as not planned by Thlumyn** 2023-12-27 16:07 UTC
Labels: not-a-bug, documentation, good first issue
