### ISSUE TITLE
[BUG] 2 kits from the same litter get the same name

### ISSUE THREAD

**Issue by KiraDragoness** [ClanGenOfficial/clangen#2268] opened 2024-04-27 11:01 UTC
**Type**: Code

**Describe the bug**
Two kits that have been born within the same litter receive the same Prefix.

**Grade**: Non-vital

**Reproduce**
Skip moons until a new litter has 2 kits with the same name.

**Screenshots**
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/716b3f19-33e7-4601-92be-80b2937e1939)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/685d7438-5097-4ba6-8cd6-f661adae36a7)
![image](https://github.com/ClanGenOfficial/clangen/assets/121829433/1a98fb9f-75f6-489d-990e-75624d3db006)

**Comment by keyraven** [comment] 2024-04-27 19:01
Note: This is currently intended behavior, as there is nothing to stop this.  That's why it's been marked as "enhancement" - fixing this "issue" would be a new limitation on kitten names.

**Comment by joesandmeyer** [comment] 2024-04-28 06:28
Fixed here at this PR: https://github.com/ClanGenOfficial/clangen/pull/2277

**Closed as completed** 2024-04-28 12:53 UTC
Labels: enhancement, good first issue
