### ISSUE TITLE
[BUG] Invisible cats on "Cat List" page

### ISSUE THREAD

**Issue by mirandarts** [ClanGenOfficial/clangen#2471] opened 2024-06-15 21:34 UTC
**Type**: (only select one)
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off. 

**Describe the bug**
On the "Cat List" page, every cat except the first row has disappeared. The cats aren't removed from the game, they are still able to be selected on patrol/choose a mate/mediator/etc. pages, but their art and names are invisible. 

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
Unsure on how to reproduce, if at all. It just happened when I timeskipped a moon, and stays even when I close out the game and even uninstall/reinstall

**Patrol ID + Outcome Print (if applicable)**:
N/A

**Commit # or Game Version Number**: 
Dev Build: 8a7f9ede

**Additional context**
N/A

**Screenshots**
<img width="619" alt="invisible" src="https://github.com/ClanGenOfficial/clangen/assets/172937440/03bb47ae-2654-42b6-bed1-0c35bf6da969">

**Comment by mirandarts** [comment] 2024-06-15 23:23
update: it was fixed for a while after closing and reopening, but 5 minutes in and it happened again. this time, every row except the 4th is visible, but the last row is invisible.
<img width="619" alt="invisible 2" src="https://github.com/ClanGenOfficial/clangen/assets/172937440/a748d54b-4525-46f8-807a-45977d8af545">

**Comment by scribblecrumb** [comment] 2024-06-15 23:32
If you can come up with any ideas to reproduce this, please let me know.  I'm unable to replicate it.

One thing we could try is seeing what your pygame_gui debug looks like.  If you can reproduce this bug and then hit F2, you should see a bunch of print messages appear.  Copy-paste the entire print message as a code block here so that I can see it, this may help give some extra info.

**Comment by j-gynn** [comment] 2024-06-15 23:38
@scribblecrumb I've successfully replicated this! It seems like newly added cats (from seemingly any source) aren't loading properly.
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/e34a691a-a9c7-4d27-968e-ee84343f3cc1)
As you can see, there he isn't.

**Comment by scribblecrumb** [comment] 2024-06-15 23:39
@j-gynn that's.... very odd.  I'll look into it.  Do the new cats show up upon timeskipping, or are they just permanently invisible?

**Comment by j-gynn** [comment] 2024-06-15 23:42
Permanently invisible, it'd seem. It's not specifically that cat, it's that slot on the display. If you change the order of the cats, that cat will appear (and whoever took that spot will disappear).
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/f5649445-47c8-4683-9d25-0ca846bfc2ad)
![image](https://github.com/ClanGenOfficial/clangen/assets/48025294/2427bdbc-8a9a-4913-8631-6619ae38895e)
Behold! The magical case of the disappearing Goldback and Erminepounce!

**Comment by selkirks** [comment] 2024-06-15 23:43
replicated this. closing out of the game caused the cats to appear again. only the first 2 rows of my cats appeared

**Comment by mirandarts** [comment] 2024-06-15 23:44
is this what you mean?


Layer: 0
-----------------------
#root_container: thickness - 8

Layer: 1
-----------------------
#text_box
#text_box
image
#text_box
#dev_watermark
#arrow_mns_closed_button
scrolling_container
#root_container: thickness - 5
#list_screen

Layer: 2
-----------------------
#open_data_directory_button
scrolling_container.vertical_scroll_bar
#root_container.#vert_scrollbar_buttons_container: thickness - 2
#root_container.#view_container: thickness - 4
#list_screen.#starclan_bg
#list_screen.#unknown_residence_bg
#list_screen.#dark_forest_bg

Layer: 3
-----------------------
#text_box_22_horizleft
scrolling_container.vertical_scroll_bar.#top_button
scrolling_container.vertical_scroll_bar.#bottom_button
scrolling_container.vertical_scroll_bar.#sliding_button
#root_container.#view_container.#scrollable_container
#cat_display_container

Layer: 4
-----------------------
scrolling_container.#mns_bg_closed
#cat_list_bar
#cat_display_container.#arrow_double_left_button
#cat_display_container.#arrow_left_button
#cat_display_container.#arrow_double_right_button
#cat_display_container.#arrow_right_button
#cat_display_container.#page_entry_box
#cat_display_container.#text_box_30_horizcenter

Layer: 5
-----------------------
#events_menu_button
#camp_menu_button
#catlist_menu_button
#patrol_menu_button
#main_menu_button
#allegiances_button
#clan_settings_button
image
image
#text_box_34_horizcenter_light
scrolling_container.#mns_image_moon
scrolling_container.#mns_image_newleaf
#cat_list_bar.#fav_cat_toggle_off
#cat_list_bar.#search_bar
#cat_list_bar.#search_entry_box
#cat_list_bar.#show_dead_button
#cat_list_bar.#choose_group_button
#cat_list_bar.#choose_group_container
#cat_list_bar.#choose_living_dropdown
#cat_list_bar.#choose_group_container
#cat_list_bar.#choose_living_dropdown
#cat_list_bar.#filter_by_rank_button
#cat_display_container.#cat_list_display.#sprite0
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite1
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite2
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite3
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite4
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite5
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite6
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite7
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite8
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite9
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite10
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite11
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite12
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite13
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite14
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite15
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite16
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite17
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite18
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter
#cat_display_container.#cat_list_display.#sprite19
#cat_display_container.#cat_list_display.#cat_button
#cat_display_container.#cat_list_display.#text_box_30_horizcenter

Layer: 6
-----------------------
#dens_button
#lead_den_button
#med_den_button
#warrior_den_button
#clearing_button
#cat_list_bar.#sort_by_button_container
#cat_list_bar.#sort_by_dropdown

Layer: 7
-----------------------
#cat_list_bar.#choose_group_container.#view_your_clan_button
#cat_list_bar.#choose_group_container.#view_cotc_button
#cat_list_bar.#choose_group_container.#view_starclan_button
#cat_list_bar.#choose_group_container.#view_unknown_residence_button
#cat_list_bar.#choose_group_container.#view_dark_forest_button
#cat_list_bar.#sort_by_button_container.#filter_rank_button
#cat_list_bar.#sort_by_button_container.#filter_age_button
#cat_list_bar.#sort_by_button_container.#filter_reverse_age_button
#cat_list_bar.#sort_by_button_container.#filter_id_button
#cat_list_bar.#sort_by_button_container.#filter_exp_button
#cat_list_bar.#sort_by_button_container.#filter_death_button

Layer: 9
-----------------------
#debug_console
#debug_console.#window_root_container: thickness - 3
#debug_console.#window_element_container: thickness - 3

Layer: 10
-----------------------
#debug_console.#command_entry
#debug_console.#log

**Comment by scribblecrumb** [comment] 2024-06-15 23:47
@j-gynn  What the heck.  Are you sure it's related to new cats?  I'm trying to replicate and all the new cats I get are showing just fine.

My first instinct would be that something is causing the cat object to have no callable sprite, but I feel like that would throw an error instead of just. disappearing.

Are you guys able to click the empty spaces and go to that cat's profile?

**Comment by mirandarts** [comment] 2024-06-15 23:50
> Are you guys able to click the empty spaces and go to that cat's profile?

nope, it doesn't do anything if you try to click the blank space. but if you go to a visible cat's profile, you can hit the "next cat" button and you will be able to view the invisible cats' page. they are still invisible on the main page though

**Closed as completed** 2024-06-16 13:58 UTC

**Comment by mirandarts** [comment] 2024-06-16 16:46
i updated the game with the recent fix in devlog but it just happened to me again :/

**Comment by Snowstar38** [comment] 2024-06-17 04:26
I can confirm, I just updated to the latest dev version with the new fix and had this happen to me:

https://github.com/ClanGenOfficial/clangen/assets/104292791/b88e83ca-759d-4422-a47f-d217755200f7

Also, the issue with the text being cut off in all other views happens if you have fewer than 4 rows in StarClan/COTC, open the profile view of a cat in them, and use the back button to return to the StarClan/COTC list. It's best replicated with a Clan of at least 1 full page and only 1 row in each StarClan and COTC.

@scribblecrumb
