### ISSUE TITLE
[BUG] Cats being cut off screen

### ISSUE THREAD

**Issue by kiwiskaatzzz** [ClanGenOfficial/clangen#2473] opened 2024-06-15 22:51 UTC
Type
- UI - anything to do with the user interface. maybe a button is not working, or the way some assets are formatted seems to be off.

Describe the bug
This bug causes the disappearance of all cats on screen except two, seemingly at random during time-skips in moons.  Names and cat sprites are cut off. This seems to only happen when there are more than two cats on screen, as the bug doesn't occur when my clan only has two cats. This also happens in both Full-screen and the minimized version of the game.

Grade: 
- Dire - Still playable, but a major feature is broken

Reproduce
1. Go to 'Events' and press 'Timeskip One Moon'
2. Go to 'Cat List' (can be either the living or dead cat list)
3. See error

Commit # or Game Version Number: 
Dev Build 0.90

Screenshots
![Screenshot 2024-06-15 6 40 01 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/35a6c704-d012-4c6a-bc7e-be0c35195e08)
![Screenshot 2024-06-15 6 39 55 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/786de411-771d-48cd-a206-76ef4cf8c0b5)
![Screenshot 2024-06-15 6 38 27 PM](https://github.com/ClanGenOfficial/clangen/assets/140553534/ac543b9e-3546-4c38-b3e9-59ad92155e75)

**Comment by scribblecrumb** [comment] 2024-06-15 23:26
Odd, I'm not experiencing this.  Can you send your save files for this Clan so that I can see if it's somehow save specific?

**Comment by scribblecrumb** [comment] 2024-06-15 23:27
Also noting this is a dupe of #2471, make sure in the future to check if a bug has already been reported!  You can add information to an existing Issue instead of creating a new one.

**Closed as completed** 2024-06-16 13:58 UTC
Labels: bug, duplicate
