### ISSUE TITLE
Dead Cats from Past Clan in New Clan

### ISSUE THREAD

**Issue by GravicRoyvi1089** [ClanGenOfficial/clangen#1963] opened 2023-12-14 00:28 UTC
I started a new Clan recently, and upon skipping a moon, I got a death message about the deaths of cats from my previous clan (which unfortunately died out).
<img width="499" alt="3B84AA5A-D5DE-41FA-875F-9647A38FF5DC" src="https://github.com/ClanGenOfficial/clangen/assets/147953341/8b9237d6-f5ba-4bb2-a913-3d026e197585">
^The cat names in this screenshot are from the past clan

**Comment by keyraven** [comment] 2024-04-01 07:37
Duplicate of #1877

**Closed as not planned by keyraven** 2024-04-01 07:37 UTC
Labels: bug
