### ISSUE TITLE
pronoun errors

### ISSUE THREAD

**Issue by peppst-r** [ClanGenOfficial/clangen#2222] opened 2024-04-18 01:09 UTC
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/3cffdac3-2f3e-4905-a302-438f8df041ec)
![image](https://github.com/ClanGenOfficial/clangen/assets/167268625/9147493f-acf6-4d8e-9dee-98bb71d4abc4)

**Comment by jdowner** [comment] 2024-05-01 23:09
I was taking a look into this to learn a bit more about the code. From the log (above) it looks like there is no 'stat cat' (not sure what that is) but, for the `fail_outcome` (`resources/dicst/patrols/forest/hunting/any.json:3068`) a stat cat is assumed to exist. At this point I'm not sure whether the problem is that there is no 'stat cat' or whether the `fail_outcome` should not be referring to the 'stat cat'.

**Comment by keyraven** [comment] 2024-05-01 23:14
> I was taking a look into this to learn a bit more about the code. From the log (above) it looks like there is no 'stat cat' (not sure what that is) but, for the `fail_outcome` (`resources/dicst/patrols/forest/hunting/any.json:3068`) a stat cat is assumed to exist. At this point I'm not sure whether the problem is that there is no 'stat cat' or whether the `fail_outcome` should not be referring to the 'stat cat'.

You are correct, the issue is either (1) there should have been a "stat" specified, making it a "stat" outcome, or (2) it should not be referring to s_c. Some patrol outcomes are blocked behind a certain skill or trait, and the cat w/ that skill or trait is called the "stat cat".   This patrol will be fixed soon, thanks for the report!

**Closed as completed** 2024-05-05 15:14 UTC
Labels: bug, issue-in-text, good first issue
