### ISSUE TITLE
[BUG] classic conditions crash game Sometimes

### ISSUE THREAD

**Issue by selkirks** [ClanGenOfficial/clangen#2868] opened 2024-10-08 21:54 UTC
**Type**: (only select one)
- Code - general bugs related to how the game runs and responds to you. 

**Describe the bug**
ive had this with running nose, grief stricken, and recovering from birth. for some reason, game crashes sometimes when a cat gets(?) condition on class mode

**Grade**: (only select one)
- Dire - Still playable, but a major feature is broken

**Reproduce**
1. start a classic clan
2. moon skip
3. eventually itll crash

**Commit # or Game Version Number**: b8da2f2fde12c2a0724e64066f525041ec9668c4

**Additional context**
Traceback (most recent call last):
  File "C:\Users\Leafy\Documents\Github\clangen\main.py", line 299, in <module>
    game.all_screens[game.current_screen].on_use()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\EventsScreen.py", line 710, in on_use
    self.loading_screen_on_use(self.events_thread, self.timeskip_done)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 150, in loading_screen_on_use
    work_thread.join()
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 25, in join
    raise self.exc
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\game_structure\propagating_thread.py", line 18, in run
    self.ret = self._target(*self._args, **self._kwargs)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 117, in _work_target
    raise exp
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\screens\Screens.py", line 111, in _work_target
    target(*args)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 133, in one_moon
    self.one_moon_cat(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events.py", line 1169, in one_moon_cat
    Condition_Events.handle_injuries(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\condition_events.py", line 340, in handle_injuries
    triggered = Condition_Events.handle_already_injured(cat)
  File "C:\Users\Leafy\Documents\Github\clangen\scripts\events_module\condition_events.py", line 679, in handle_already_injured
    cat.injuries.pop(injury)
KeyError: 'recovering from birth'

**Comment by larkgz** [comment] 2024-10-26 03:31
It seems like this is the same issue as with #2938. Unsure if it relates to Classic mode specifically.

**Comment by j-gynn** [comment] 2024-11-23 22:23
Possibly duplicate of #2857 - let me know if this was not as a result of spam-clicking timeskips and we'll look into it further :)

**Closed as completed** 2024-11-23 23:49 UTC
Labels: bug
